using FSGAP.Abstractions.Failures;
using FSGAP.Synaptic.Degradations;
using FSGAP.Synaptic.Systems;

namespace FSGAP.Synaptic.Failures;

/// <summary>
/// Engineering provenance of a recipe, kept for traceability and for the later qualification report. It never gates
/// execution: <see cref="Validated"/>, <see cref="Assumed"/> and <see cref="Approximation"/> recipes all execute;
/// <see cref="Unmapped"/> means no documented Synaptic control exists, so the key is listed but not executable.
/// </summary>
internal enum SynapticFailureQualification
{
    /// <summary>The control was written, observed in the cockpit and restored live.</summary>
    Validated,

    /// <summary>A documented control matching the failure; not yet exercised live.</summary>
    Assumed,

    /// <summary>The closest coherent documented degradation; the operational effect only approximates the failure.</summary>
    Approximation,

    /// <summary>No documented Synaptic control: listed for catalog parity, <c>Operations = None</c>.</summary>
    Unmapped,
}

/// <summary>How a recipe acts on the aircraft.</summary>
internal enum SynapticFailureMechanism
{
    /// <summary>The single control of one of the public controlled degradations (shared registry control and board).</summary>
    ControlledDegradation,

    /// <summary>One other registry control.</summary>
    LocalVariableState,

    /// <summary>Several registry controls, applied and restored together.</summary>
    CompositeSystemState,

    /// <summary>No mechanism (unmapped key).</summary>
    None,
}

/// <summary>
/// One normalized failure on the Synaptic A220: the same definition as the Fenix key (key, display name, category,
/// target), the registry controls it forces, and its provenance. Raw A22X names stay in <see cref="SynapticControls"/>.
/// </summary>
internal sealed record SynapticFailureRecipe(FailureDefinition Definition, SynapticFailureQualification Qualification, string Effect, IReadOnlyList<SynapticControl> Controls)
{
    public FailureKey Key => Definition.Key;

    public bool Executable => Controls.Count > 0;

    public SynapticFailureMechanism Mechanism =>
        Controls.Count == 0 ? SynapticFailureMechanism.None
        : Controls.Count > 1 ? SynapticFailureMechanism.CompositeSystemState
        : SynapticDegradationControls.Controls.Any(d => ReferenceEquals(d.Control, Controls[0])) ? SynapticFailureMechanism.ControlledDegradation
        : SynapticFailureMechanism.LocalVariableState;
}

/// <summary>
/// The Synaptic A220 failure catalog: exactly the normalized keys of the Fenix catalog, 384 since 0.12.0-preview.4 (same
/// display names, categories and targets), each with one recipe. Generated from the Fenix mapping resource; the parity is
/// enforced by tests. Catalog parity is not execution parity: 17 recipes act, the others are listed with Operations = None.
/// </summary>
/// <remarks>
/// Executable recipes force documented cockpit controls (see <see cref="SynapticControls"/>): the failure is the aircraft
/// put into a degraded configuration, not a diagnosed hardware fault. No native simulator failure event is used. Keys with
/// no documented control are listed with <c>Operations = None</c> (a trigger answers <c>NotSupported</c>), so consumers see
/// the same key set on every aircraft and which ones act.
/// </remarks>
internal static class SynapticFailureCatalog
{
    private const FailureOperations Both = FailureOperations.Trigger | FailureOperations.Clear;

    internal static readonly IReadOnlyList<SynapticFailureRecipe> Recipes =
    [
        F("air-conditioning.cpc.1", "Cabin pressure controller 1", FailureCategory.AirConditioning, FailureTarget.Aircraft, SynapticFailureQualification.Approximation, "automatic pressurization replaced by manual mode (cabin pressure controller out of the loop)", SynapticControls.ManualPressurization),
        F("air-conditioning.pack.1.overheat", "Pack 1 overheat", FailureCategory.AirConditioning, FailureTarget.Aircraft, SynapticFailureQualification.Approximation, "left pack shut down, as after an overheat (live-validated control)", SynapticControls.LeftPackOff),
        F("air-conditioning.pack.1.regulator-fault", "Pack 1 regulator fault", FailureCategory.AirConditioning, FailureTarget.Aircraft, SynapticFailureQualification.Approximation, "trim air off: zone temperature regulation lost", SynapticControls.TrimAirOff),
        F("electrical.static-inverter", "Static inverter", FailureCategory.Electrical, FailureTarget.Aircraft, SynapticFailureQualification.Unmapped, "no documented Synaptic control"),
        F("electrical.generator.1", "Generator 1 (IDG 1 drive)", FailureCategory.Electrical, FailureTarget.Aircraft, SynapticFailureQualification.Validated, "left generator off line (live-validated control)", SynapticControls.LeftGeneratorOff),
        F("electrical.generator.2", "Generator 2 (IDG 2 drive)", FailureCategory.Electrical, FailureTarget.Aircraft, SynapticFailureQualification.Assumed, "right generator off line", SynapticControls.RightGeneratorOff),
        F("electrical.bus.ac-1", "AC bus 1", FailureCategory.Electrical, FailureTarget.ElectricalBus("ac-1"), SynapticFailureQualification.Unmapped, "no documented Synaptic control"),
        F("electrical.bus.ac-ess", "AC essential bus", FailureCategory.Electrical, FailureTarget.ElectricalBus("ac-ess"), SynapticFailureQualification.Unmapped, "no documented Synaptic control"),
        F("electrical.bus.dc-1", "DC bus 1", FailureCategory.Electrical, FailureTarget.ElectricalBus("dc-1"), SynapticFailureQualification.Unmapped, "no documented Synaptic control"),
        F("electrical.bus.dc-2", "DC bus 2", FailureCategory.Electrical, FailureTarget.ElectricalBus("dc-2"), SynapticFailureQualification.Unmapped, "no documented Synaptic control"),
        F("electrical.bus.dc-bat", "DC battery bus", FailureCategory.Electrical, FailureTarget.ElectricalBus("dc-bat"), SynapticFailureQualification.Unmapped, "no documented Synaptic control"),
        F("fire.lavatory.smoke", "Lavatory smoke", FailureCategory.Fire, FailureTarget.Aircraft, SynapticFailureQualification.Unmapped, "no documented Synaptic control"),
        F("fire.engine.1.loop-a", "Engine 1 fire detection loop A", FailureCategory.Fire, FailureTarget.Engine(1), SynapticFailureQualification.Unmapped, "no documented Synaptic control"),
        F("fire.fdu.1", "Fire detection unit 1", FailureCategory.Fire, FailureTarget.Aircraft, SynapticFailureQualification.Unmapped, "no documented Synaptic control"),
        F("fuel.fqi.channel-2", "Fuel quantity indication channel 2", FailureCategory.Fuel, FailureTarget.Aircraft, SynapticFailureQualification.Unmapped, "no documented Synaptic control"),
        F("fuel.pump.left-1", "Left tank fuel pump 1", FailureCategory.Fuel, FailureTarget.FuelPump("left-1"), SynapticFailureQualification.Assumed, "left boost pump selector off", SynapticControls.LeftBoostPump),
        F("fuel.pump.right-1", "Right tank fuel pump 1", FailureCategory.Fuel, FailureTarget.FuelPump("right-1"), SynapticFailureQualification.Assumed, "right boost pump selector off", SynapticControls.RightBoostPump),
        F("hydraulic.blue.electric-pump", "Blue electric hydraulic pump", FailureCategory.Hydraulic, FailureTarget.HydraulicSystem("blue"), SynapticFailureQualification.Validated, "system 3 pump 3A off, 3B takes over (A320 blue ~ A220 system 3; live-validated control)", SynapticControls.HydraulicPump3A),
        F("hydraulic.yellow.electric-pump", "Yellow electric hydraulic pump", FailureCategory.Hydraulic, FailureTarget.HydraulicSystem("yellow"), SynapticFailureQualification.Assumed, "system 2 AC motor pump 2B off (A320 yellow ~ A220 system 2)", SynapticControls.HydraulicPump2B),
        F("hydraulic.blue.low-level", "Blue hydraulic reservoir low level", FailureCategory.Hydraulic, FailureTarget.HydraulicSystem("blue"), SynapticFailureQualification.Approximation, "both system 3 pumps off: system 3 unpressurized", SynapticControls.HydraulicPump3A, SynapticControls.HydraulicPump3B),
        F("hydraulic.green.low-level", "Green hydraulic reservoir low level", FailureCategory.Hydraulic, FailureTarget.HydraulicSystem("green"), SynapticFailureQualification.Approximation, "system 1 shutoff valve switch to its non-normal position (A320 green ~ A220 system 1)", SynapticControls.Hydraulic1ShutoffValve),
        F("hydraulic.blue.leak", "Blue hydraulic leak", FailureCategory.Hydraulic, FailureTarget.HydraulicSystem("blue"), SynapticFailureQualification.Approximation, "both system 3 pumps off: system 3 unpressurized", SynapticControls.HydraulicPump3A, SynapticControls.HydraulicPump3B),
        F("hydraulic.green.leak", "Green hydraulic leak", FailureCategory.Hydraulic, FailureTarget.HydraulicSystem("green"), SynapticFailureQualification.Approximation, "system 1 shutoff valve switch to its non-normal position and PTU off", SynapticControls.Hydraulic1ShutoffValve, SynapticControls.PowerTransferUnit),
        F("ice-rain.aoa-heat.standby", "Standby AOA probe heat", FailureCategory.IceAndRain, FailureTarget.Aircraft, SynapticFailureQualification.Unmapped, "no documented Synaptic control"),
        F("ice-rain.pitot-heat.fo", "First officer pitot heat", FailureCategory.IceAndRain, FailureTarget.Aircraft, SynapticFailureQualification.Unmapped, "no documented Synaptic control"),
        F("indicating.display.ecam-lower", "Lower ECAM display unit", FailureCategory.Instruments, FailureTarget.Aircraft, SynapticFailureQualification.Approximation, "lower display brightness to zero (display dark)", SynapticControls.LowerDisplayBrightness),
        F("landing-gear.brake.wheel-1", "Wheel 1 brake fault", FailureCategory.LandingGear, FailureTarget.Aircraft, SynapticFailureQualification.Approximation, "alternate brake mode selected: normal brake control degraded (no side-specific brake isolation is documented)", SynapticControls.AlternateBrake),
        F("landing-gear.tyre-pressure.main-1", "Main tyre 1 low pressure", FailureCategory.LandingGear, FailureTarget.Aircraft, SynapticFailureQualification.Unmapped, "no documented Synaptic control"),
        F("landing-gear.tyre-pressure.right-1", "Right tyre 1 low pressure", FailureCategory.LandingGear, FailureTarget.Aircraft, SynapticFailureQualification.Unmapped, "no documented Synaptic control"),
        F("navigation.fmgc.1", "FMGC 1", FailureCategory.Navigation, FailureTarget.Aircraft, SynapticFailureQualification.Unmapped, "no documented Synaptic control"),
        F("navigation.mcdu.1.recoverable-fault", "MCDU 1 recoverable fault", FailureCategory.Navigation, FailureTarget.Aircraft, SynapticFailureQualification.Unmapped, "no documented Synaptic control"),
        F("navigation.adf.1", "ADF 1", FailureCategory.Navigation, FailureTarget.Aircraft, SynapticFailureQualification.Unmapped, "no documented Synaptic control"),
        F("navigation.gps.1", "GPS 1", FailureCategory.Navigation, FailureTarget.Aircraft, SynapticFailureQualification.Unmapped, "no documented Synaptic control"),
        F("navigation.ils.1.localizer", "ILS 1 localizer", FailureCategory.Navigation, FailureTarget.Aircraft, SynapticFailureQualification.Unmapped, "no documented Synaptic control"),
        F("pneumatic.bleed-valve.1", "Engine 1 bleed valve", FailureCategory.Pneumatic, FailureTarget.Aircraft, SynapticFailureQualification.Assumed, "left engine bleed off", SynapticControls.LeftBleedOff),
        F("doors.entry.forward-left", "Forward left entry door", FailureCategory.Doors, FailureTarget.Aircraft, SynapticFailureQualification.Unmapped, "no documented Synaptic control"),
        F("doors.entry.aft-left", "Aft left entry door", FailureCategory.Doors, FailureTarget.Aircraft, SynapticFailureQualification.Unmapped, "no documented Synaptic control"),
        F("engine.1.surge", "Engine 1 surge", FailureCategory.Engine, FailureTarget.Engine(1), SynapticFailureQualification.Unmapped, "no documented Synaptic control"),
        F("engine.1.vibration.n1", "Engine 1 high N1 vibration", FailureCategory.Engine, FailureTarget.Engine(1), SynapticFailureQualification.Unmapped, "no documented Synaptic control"),
        F("engine.1.eiu", "Engine 1 interface unit (EIU 1)", FailureCategory.Engine, FailureTarget.Engine(1), SynapticFailureQualification.Approximation, "engine 1 services to the aircraft cut: left generator and left bleed off", SynapticControls.LeftGeneratorOff, SynapticControls.LeftBleedOff),

        // BLOCK 12.2: the 344 keys normalized in 0.12.0-preview.4 (generated from the Fenix mapping). No documented Synaptic
        // control is known for any of them: listed for catalog parity, Operations = None.
        U("air-conditioning.cpc.2", "Cabin pressure controller 2", FailureCategory.AirConditioning, FailureTarget.Aircraft),
        U("air-conditioning.pack.2.overheat", "Pack 2 overheat", FailureCategory.AirConditioning, FailureTarget.Aircraft),
        U("air-conditioning.pack.2.regulator-fault", "Pack 2 regulator fault", FailureCategory.AirConditioning, FailureTarget.Aircraft),
        U("air-conditioning.zone-controller.primary", "Zone controller primary channel", FailureCategory.AirConditioning, FailureTarget.Aircraft),
        U("air-conditioning.zone-controller.secondary", "Zone controller secondary channel", FailureCategory.AirConditioning, FailureTarget.Aircraft),
        U("air-conditioning.trim-air.hot-air-fault", "Trim air hot air fault", FailureCategory.AirConditioning, FailureTarget.Aircraft),
        U("air-conditioning.cargo-ventilation-controller", "Cargo ventilation controller", FailureCategory.AirConditioning, FailureTarget.Aircraft),
        U("air-conditioning.cargo.aft.hot-air-valve", "Aft cargo hot air valve", FailureCategory.AirConditioning, FailureTarget.Aircraft),
        U("air-conditioning.cargo.forward.isolation-valve.upstream", "Forward cargo isolation valve, upstream", FailureCategory.AirConditioning, FailureTarget.Aircraft),
        U("air-conditioning.cargo.forward.isolation-valve.downstream", "Forward cargo isolation valve, downstream", FailureCategory.AirConditioning, FailureTarget.Aircraft),
        U("air-conditioning.cargo.aft.isolation-valve.upstream", "Aft cargo isolation valve, upstream", FailureCategory.AirConditioning, FailureTarget.Aircraft),
        U("air-conditioning.cargo.aft.isolation-valve.downstream", "Aft cargo isolation valve, downstream", FailureCategory.AirConditioning, FailureTarget.Aircraft),
        U("air-conditioning.recirculation-fans", "Recirculation fans", FailureCategory.AirConditioning, FailureTarget.Aircraft),
        U("air-conditioning.decompression.slow", "Slow decompression", FailureCategory.AirConditioning, FailureTarget.Aircraft),
        U("air-conditioning.decompression.rapid", "Rapid decompression", FailureCategory.AirConditioning, FailureTarget.Aircraft),
        U("air-conditioning.outflow-valve.stuck", "Outflow valve stuck", FailureCategory.AirConditioning, FailureTarget.Aircraft),
        U("air-conditioning.ventilation.aevc", "Avionics equipment ventilation controller", FailureCategory.AirConditioning, FailureTarget.Aircraft),
        U("air-conditioning.ventilation.blower", "Ventilation blower fault", FailureCategory.AirConditioning, FailureTarget.Aircraft),
        U("air-conditioning.ventilation.extract", "Ventilation extract fault", FailureCategory.AirConditioning, FailureTarget.Aircraft),
        U("air-conditioning.ventilation.inlet-valve", "Ventilation inlet valve", FailureCategory.AirConditioning, FailureTarget.Aircraft),
        U("air-conditioning.ventilation.extract-valve", "Ventilation extract valve", FailureCategory.AirConditioning, FailureTarget.Aircraft),
        U("auto-flight.fac.1", "FAC 1", FailureCategory.Autoflight, FailureTarget.Aircraft),
        U("auto-flight.fac.2", "FAC 2", FailureCategory.Autoflight, FailureTarget.Aircraft),
        U("auto-flight.fac.1.resettable-fault", "FAC 1 resettable fault", FailureCategory.Autoflight, FailureTarget.Aircraft),
        U("auto-flight.fac.2.resettable-fault", "FAC 2 resettable fault", FailureCategory.Autoflight, FailureTarget.Aircraft),
        U("auto-flight.rudder-travel-limiter.1", "Rudder travel limiter channel 1", FailureCategory.Autoflight, FailureTarget.Aircraft),
        U("auto-flight.rudder-travel-limiter.2", "Rudder travel limiter channel 2", FailureCategory.Autoflight, FailureTarget.Aircraft),
        U("auto-flight.rudder-trim.1", "Rudder trim channel 1", FailureCategory.Autoflight, FailureTarget.Aircraft),
        U("auto-flight.rudder-trim.2", "Rudder trim channel 2", FailureCategory.Autoflight, FailureTarget.Aircraft),
        U("auto-flight.windshear-detection.1", "Reactive windshear detection channel 1", FailureCategory.Autoflight, FailureTarget.Aircraft),
        U("auto-flight.windshear-detection.2", "Reactive windshear detection channel 2", FailureCategory.Autoflight, FailureTarget.Aircraft),
        U("auto-flight.law.alternate-protected", "Alternate law with protection", FailureCategory.Autoflight, FailureTarget.Aircraft),
        U("auto-flight.law.alternate-unprotected", "Alternate law without protection", FailureCategory.Autoflight, FailureTarget.Aircraft),
        U("auto-flight.law.direct", "Direct law", FailureCategory.Autoflight, FailureTarget.Aircraft),
        U("auto-flight.fcu.channel-1", "FCU channel 1", FailureCategory.Autoflight, FailureTarget.Aircraft),
        U("auto-flight.fcu.channel-2", "FCU channel 2", FailureCategory.Autoflight, FailureTarget.Aircraft),
        U("auto-flight.autothrust.1", "Autothrust 1", FailureCategory.Autoflight, FailureTarget.Aircraft),
        U("auto-flight.autothrust.2", "Autothrust 2", FailureCategory.Autoflight, FailureTarget.Aircraft),
        U("auto-flight.autopilot.1", "Autopilot 1", FailureCategory.Autoflight, FailureTarget.Aircraft),
        U("auto-flight.autopilot.2", "Autopilot 2", FailureCategory.Autoflight, FailureTarget.Aircraft),
        U("electrical.bus.hot-1", "Hot bus 1", FailureCategory.Electrical, FailureTarget.ElectricalBus("hot-1")),
        U("electrical.bus.hot-2", "Hot bus 2", FailureCategory.Electrical, FailureTarget.ElectricalBus("hot-2")),
        U("electrical.bus.dc-ess", "DC essential bus", FailureCategory.Electrical, FailureTarget.ElectricalBus("dc-ess")),
        U("electrical.bus.dc-ess-shed", "DC essential shed bus", FailureCategory.Electrical, FailureTarget.ElectricalBus("dc-ess-shed")),
        U("electrical.bus.ac-2", "AC bus 2", FailureCategory.Electrical, FailureTarget.ElectricalBus("ac-2")),
        U("electrical.bus.ac-ess-shed", "AC essential shed bus", FailureCategory.Electrical, FailureTarget.ElectricalBus("ac-ess-shed")),
        U("electrical.bus.ac-static-inverter", "AC static inverter bus", FailureCategory.Electrical, FailureTarget.ElectricalBus("ac-static-inverter")),
        U("electrical.bus.ac-1-26v", "AC bus 1, 26 V", FailureCategory.Electrical, FailureTarget.ElectricalBus("ac-1-26v")),
        U("electrical.bus.ac-2-26v", "AC bus 2, 26 V", FailureCategory.Electrical, FailureTarget.ElectricalBus("ac-2-26v")),
        U("electrical.bus.ac-ess-26v", "AC essential bus, 26 V", FailureCategory.Electrical, FailureTarget.ElectricalBus("ac-ess-26v")),
        U("electrical.generator.apu", "APU generator", FailureCategory.Electrical, FailureTarget.Apu),
        U("electrical.idg.1.oil-overheat", "IDG 1 oil overheat", FailureCategory.Electrical, FailureTarget.Aircraft),
        U("electrical.idg.2.oil-overheat", "IDG 2 oil overheat", FailureCategory.Electrical, FailureTarget.Aircraft),
        U("electrical.idg.1.oil-low-pressure", "IDG 1 oil low pressure", FailureCategory.Electrical, FailureTarget.Aircraft),
        U("electrical.idg.2.oil-low-pressure", "IDG 2 oil low pressure", FailureCategory.Electrical, FailureTarget.Aircraft),
        U("electrical.transformer-rectifier.1", "Transformer rectifier 1", FailureCategory.Electrical, FailureTarget.Aircraft),
        U("electrical.transformer-rectifier.2", "Transformer rectifier 2", FailureCategory.Electrical, FailureTarget.Aircraft),
        U("electrical.transformer-rectifier.ess", "Essential transformer rectifier", FailureCategory.Electrical, FailureTarget.Aircraft),
        U("electrical.ac-ess-feed.alternate", "AC essential bus alternate feed", FailureCategory.Electrical, FailureTarget.Aircraft),
        U("electrical.ac-ess-feed.ac-1", "AC essential feed from AC bus 1", FailureCategory.Electrical, FailureTarget.Aircraft),
        U("electrical.ac-ess-feed.ac-2", "AC essential feed from AC bus 2", FailureCategory.Electrical, FailureTarget.Aircraft),
        U("fire.sdcu", "Smoke detection control unit", FailureCategory.Fire, FailureTarget.Aircraft),
        U("fire.cargo.forward.smoke", "Forward cargo smoke detected", FailureCategory.Fire, FailureTarget.Aircraft),
        U("fire.cargo.aft.smoke", "Aft cargo smoke detected", FailureCategory.Fire, FailureTarget.Aircraft),
        U("fire.engine.1.unextinguishable", "Engine 1 unextinguishable fire", FailureCategory.Fire, FailureTarget.Engine(1)),
        U("fire.engine.2.unextinguishable", "Engine 2 unextinguishable fire", FailureCategory.Fire, FailureTarget.Engine(2)),
        U("fire.apu.unextinguishable", "APU unextinguishable fire", FailureCategory.Fire, FailureTarget.Apu),
        U("fire.engine.1.extinguished-one-bottle", "Engine 1 fire, extinguished with one bottle", FailureCategory.Fire, FailureTarget.Engine(1)),
        U("fire.engine.2.extinguished-one-bottle", "Engine 2 fire, extinguished with one bottle", FailureCategory.Fire, FailureTarget.Engine(2)),
        U("fire.apu.extinguished-one-bottle", "APU fire, extinguished with one bottle", FailureCategory.Fire, FailureTarget.Apu),
        U("fire.engine.1.extinguished-two-bottles", "Engine 1 fire, extinguished with two bottles", FailureCategory.Fire, FailureTarget.Engine(1)),
        U("fire.engine.2.extinguished-two-bottles", "Engine 2 fire, extinguished with two bottles", FailureCategory.Fire, FailureTarget.Engine(2)),
        U("fire.engine.1.loop-b", "Engine 1 fire detection loop B", FailureCategory.Fire, FailureTarget.Engine(1)),
        U("fire.engine.2.loop-a", "Engine 2 fire detection loop A", FailureCategory.Fire, FailureTarget.Engine(2)),
        U("fire.engine.2.loop-b", "Engine 2 fire detection loop B", FailureCategory.Fire, FailureTarget.Engine(2)),
        U("fire.apu.loop-a", "APU fire detection loop A", FailureCategory.Fire, FailureTarget.Apu),
        U("fire.apu.loop-b", "APU fire detection loop B", FailureCategory.Fire, FailureTarget.Apu),
        U("fire.fdu.2", "Fire detection unit 2", FailureCategory.Fire, FailureTarget.Aircraft),
        U("fire.fdu.3", "Fire detection unit 3", FailureCategory.Fire, FailureTarget.Aircraft),
        U("fire.avionics.smoke", "Avionics smoke detected", FailureCategory.Fire, FailureTarget.Aircraft),
        U("fuel.fqi.channel-1", "Fuel quantity indication channel 1", FailureCategory.Fuel, FailureTarget.Aircraft),
        U("fuel.pump.left-2", "Left tank fuel pump 2", FailureCategory.Fuel, FailureTarget.FuelPump("left-2")),
        U("fuel.pump.center-1", "Center tank fuel pump 1", FailureCategory.Fuel, FailureTarget.FuelPump("center-1")),
        U("fuel.pump.center-2", "Center tank fuel pump 2", FailureCategory.Fuel, FailureTarget.FuelPump("center-2")),
        U("fuel.pump.right-2", "Right tank fuel pump 2", FailureCategory.Fuel, FailureTarget.FuelPump("right-2")),
        U("fuel.inner-tank.high-temperature.ecam", "Inner tank high fuel temperature (ECAM)", FailureCategory.Fuel, FailureTarget.Aircraft),
        U("fuel.outer-tank.high-temperature.ecam", "Outer tank high fuel temperature (ECAM)", FailureCategory.Fuel, FailureTarget.Aircraft),
        U("fuel.inner-tank.high-temperature.advisory", "Inner tank high fuel temperature (advisory)", FailureCategory.Fuel, FailureTarget.Aircraft),
        U("fuel.outer-tank.high-temperature.advisory", "Outer tank high fuel temperature (advisory)", FailureCategory.Fuel, FailureTarget.Aircraft),
        U("fuel.inner-tank.low-temperature.ecam", "Inner tank low fuel temperature (ECAM)", FailureCategory.Fuel, FailureTarget.Aircraft),
        U("fuel.outer-tank.low-temperature.ecam", "Outer tank low fuel temperature (ECAM)", FailureCategory.Fuel, FailureTarget.Aircraft),
        U("fuel.inner-tank.low-temperature.advisory", "Inner tank low fuel temperature (advisory)", FailureCategory.Fuel, FailureTarget.Aircraft),
        U("fuel.outer-tank.low-temperature.advisory", "Outer tank low fuel temperature (advisory)", FailureCategory.Fuel, FailureTarget.Aircraft),
        U("fuel.transfer-valve.left-1", "Left transfer valve 1", FailureCategory.Fuel, FailureTarget.Aircraft),
        U("fuel.transfer-valve.left-2", "Left transfer valve 2", FailureCategory.Fuel, FailureTarget.Aircraft),
        U("fuel.transfer-valve.right-1", "Right transfer valve 1", FailureCategory.Fuel, FailureTarget.Aircraft),
        U("fuel.transfer-valve.right-2", "Right transfer valve 2", FailureCategory.Fuel, FailureTarget.Aircraft),
        U("fuel.engine-valve.1.stuck", "Engine 1 fuel valve stuck", FailureCategory.Fuel, FailureTarget.Aircraft),
        U("fuel.engine-valve.2.stuck", "Engine 2 fuel valve stuck", FailureCategory.Fuel, FailureTarget.Aircraft),
        U("fuel.crossfeed-valve", "Crossfeed valve", FailureCategory.Fuel, FailureTarget.Aircraft),
        U("fuel.defuel-transfer-valve", "Defuel/transfer valve", FailureCategory.Fuel, FailureTarget.Aircraft),
        U("fuel.leak.left-outer", "Fuel leak, left outer tank", FailureCategory.Fuel, FailureTarget.Aircraft),
        U("fuel.leak.left-inner", "Fuel leak, left inner tank", FailureCategory.Fuel, FailureTarget.Aircraft),
        U("fuel.leak.center", "Fuel leak, center tank", FailureCategory.Fuel, FailureTarget.Aircraft),
        U("fuel.leak.right-inner", "Fuel leak, right inner tank", FailureCategory.Fuel, FailureTarget.Aircraft),
        U("fuel.leak.right-outer", "Fuel leak, right outer tank", FailureCategory.Fuel, FailureTarget.Aircraft),
        U("fuel.hp-valve.1", "Engine 1 HP fuel valve", FailureCategory.Fuel, FailureTarget.Aircraft),
        U("fuel.hp-valve.2", "Engine 2 HP fuel valve", FailureCategory.Fuel, FailureTarget.Aircraft),
        U("hydraulic.yellow.leak", "Yellow hydraulic leak", FailureCategory.Hydraulic, FailureTarget.HydraulicSystem("yellow")),
        U("hydraulic.green.reservoir-overheat", "Green reservoir overheat", FailureCategory.Hydraulic, FailureTarget.HydraulicSystem("green")),
        U("hydraulic.blue.reservoir-overheat", "Blue reservoir overheat", FailureCategory.Hydraulic, FailureTarget.HydraulicSystem("blue")),
        U("hydraulic.yellow.reservoir-overheat", "Yellow reservoir overheat", FailureCategory.Hydraulic, FailureTarget.HydraulicSystem("yellow")),
        U("hydraulic.green.reservoir-low-air-pressure", "Green reservoir low air pressure", FailureCategory.Hydraulic, FailureTarget.HydraulicSystem("green")),
        U("hydraulic.blue.reservoir-low-air-pressure", "Blue reservoir low air pressure", FailureCategory.Hydraulic, FailureTarget.HydraulicSystem("blue")),
        U("hydraulic.yellow.reservoir-low-air-pressure", "Yellow reservoir low air pressure", FailureCategory.Hydraulic, FailureTarget.HydraulicSystem("yellow")),
        U("hydraulic.yellow.low-level", "Yellow hydraulic reservoir low level", FailureCategory.Hydraulic, FailureTarget.HydraulicSystem("yellow")),
        U("hydraulic.engine-pump.1", "Engine 1 hydraulic pump", FailureCategory.Hydraulic, FailureTarget.Aircraft),
        U("hydraulic.engine-pump.2", "Engine 2 hydraulic pump", FailureCategory.Hydraulic, FailureTarget.Aircraft),
        U("hydraulic.fire-valve.1", "Engine 1 hydraulic fire valve", FailureCategory.Hydraulic, FailureTarget.Aircraft),
        U("hydraulic.fire-valve.2", "Engine 2 hydraulic fire valve", FailureCategory.Hydraulic, FailureTarget.Aircraft),
        U("hydraulic.ptu", "Power transfer unit fault", FailureCategory.Hydraulic, FailureTarget.Aircraft),
        U("hydraulic.blue.electric-pump.overheat", "Blue electric hydraulic pump overheat", FailureCategory.Hydraulic, FailureTarget.HydraulicSystem("blue")),
        U("hydraulic.yellow.electric-pump.overheat", "Yellow electric hydraulic pump overheat", FailureCategory.Hydraulic, FailureTarget.HydraulicSystem("yellow")),
        U("landing-gear.bscu.1", "BSCU system 1", FailureCategory.LandingGear, FailureTarget.Aircraft),
        U("landing-gear.bscu.2", "BSCU system 2", FailureCategory.LandingGear, FailureTarget.Aircraft),
        U("landing-gear.abcu", "Alternate braking control unit", FailureCategory.LandingGear, FailureTarget.Aircraft),
        U("landing-gear.bscu.1.brake-fault", "BSCU 1 brake fault", FailureCategory.LandingGear, FailureTarget.Aircraft),
        U("landing-gear.bscu.2.brake-fault", "BSCU 2 brake fault", FailureCategory.LandingGear, FailureTarget.Aircraft),
        U("landing-gear.autobrake", "Autobrake failure", FailureCategory.LandingGear, FailureTarget.Aircraft),
        U("landing-gear.brake.wheel-2", "Wheel 2 brake fault", FailureCategory.LandingGear, FailureTarget.Aircraft),
        U("landing-gear.brake.wheel-3", "Wheel 3 brake fault", FailureCategory.LandingGear, FailureTarget.Aircraft),
        U("landing-gear.brake.wheel-4", "Wheel 4 brake fault", FailureCategory.LandingGear, FailureTarget.Aircraft),
        U("landing-gear.tyre-pressure.main-2", "Main tyre 2 low pressure", FailureCategory.LandingGear, FailureTarget.Aircraft),
        U("landing-gear.tyre-pressure.left-1", "Left tyre 1 low pressure", FailureCategory.LandingGear, FailureTarget.Aircraft),
        U("landing-gear.tyre-pressure.left-2", "Left tyre 2 low pressure", FailureCategory.LandingGear, FailureTarget.Aircraft),
        U("landing-gear.tyre-pressure.right-2", "Right tyre 2 low pressure", FailureCategory.LandingGear, FailureTarget.Aircraft),
        U("landing-gear.nose-wheel-steering", "Nose wheel steering", FailureCategory.LandingGear, FailureTarget.Aircraft),
        U("landing-gear.lgciu.1", "LGCIU 1", FailureCategory.LandingGear, FailureTarget.Aircraft),
        U("landing-gear.lgciu.2", "LGCIU 2", FailureCategory.LandingGear, FailureTarget.Aircraft),
        U("landing-gear.safety-valve", "Gear safety valve", FailureCategory.LandingGear, FailureTarget.Aircraft),
        U("landing-gear.lock.left-main", "Left main gear does not lock", FailureCategory.LandingGear, FailureTarget.Aircraft),
        U("landing-gear.lock.nose", "Nose gear does not lock", FailureCategory.LandingGear, FailureTarget.Aircraft),
        U("landing-gear.lock.right-main", "Right main gear does not lock", FailureCategory.LandingGear, FailureTarget.Aircraft),
        U("landing-gear.gear.locked-up", "Gear locked up", FailureCategory.LandingGear, FailureTarget.Aircraft),
        U("landing-gear.gear.locked-down", "Gear locked down", FailureCategory.LandingGear, FailureTarget.Aircraft),
        U("navigation.ir.1.failure", "IR 1 failure", FailureCategory.Navigation, FailureTarget.InertialReference(1)),
        U("navigation.ir.2.failure", "IR 2 failure", FailureCategory.Navigation, FailureTarget.InertialReference(2)),
        U("navigation.ir.3.failure", "IR 3 failure", FailureCategory.Navigation, FailureTarget.InertialReference(3)),
        U("navigation.ir.1.position-failure", "IR 1 position failure", FailureCategory.Navigation, FailureTarget.InertialReference(1)),
        U("navigation.ir.2.position-failure", "IR 2 position failure", FailureCategory.Navigation, FailureTarget.InertialReference(2)),
        U("navigation.ir.3.position-failure", "IR 3 position failure", FailureCategory.Navigation, FailureTarget.InertialReference(3)),
        U("navigation.adr.1", "ADR 1 failure", FailureCategory.Navigation, FailureTarget.Aircraft),
        U("navigation.adr.2", "ADR 2 failure", FailureCategory.Navigation, FailureTarget.Aircraft),
        U("navigation.adr.3", "ADR 3 failure", FailureCategory.Navigation, FailureTarget.Aircraft),
        U("navigation.ir.1.alignment", "IR 1 alignment fault", FailureCategory.Navigation, FailureTarget.InertialReference(1)),
        U("navigation.ir.2.alignment", "IR 2 alignment fault", FailureCategory.Navigation, FailureTarget.InertialReference(2)),
        U("navigation.ir.3.alignment", "IR 3 alignment fault", FailureCategory.Navigation, FailureTarget.InertialReference(3)),
        U("navigation.pitot.captain.blocked", "Captain pitot blocked", FailureCategory.Navigation, FailureTarget.Aircraft),
        U("navigation.pitot.fo.blocked", "First officer pitot blocked", FailureCategory.Navigation, FailureTarget.Aircraft),
        U("navigation.pitot.standby.blocked", "Standby pitot blocked", FailureCategory.Navigation, FailureTarget.Aircraft),
        U("navigation.ir.1.pitch-discrepancy", "IR 1 pitch discrepancy", FailureCategory.Navigation, FailureTarget.InertialReference(1)),
        U("navigation.ir.2.pitch-discrepancy", "IR 2 pitch discrepancy", FailureCategory.Navigation, FailureTarget.InertialReference(2)),
        U("navigation.ir.3.pitch-discrepancy", "IR 3 pitch discrepancy", FailureCategory.Navigation, FailureTarget.InertialReference(3)),
        U("navigation.ir.1.bank-discrepancy", "IR 1 bank discrepancy", FailureCategory.Navigation, FailureTarget.InertialReference(1)),
        U("navigation.ir.2.bank-discrepancy", "IR 2 bank discrepancy", FailureCategory.Navigation, FailureTarget.InertialReference(2)),
        U("navigation.ir.3.bank-discrepancy", "IR 3 bank discrepancy", FailureCategory.Navigation, FailureTarget.InertialReference(3)),
        U("navigation.ir.1.heading-discrepancy", "IR 1 heading discrepancy", FailureCategory.Navigation, FailureTarget.InertialReference(1)),
        U("navigation.ir.2.heading-discrepancy", "IR 2 heading discrepancy", FailureCategory.Navigation, FailureTarget.InertialReference(2)),
        U("navigation.ir.3.heading-discrepancy", "IR 3 heading discrepancy", FailureCategory.Navigation, FailureTarget.InertialReference(3)),
        U("navigation.ir.1.disagree", "IR 1 disagree", FailureCategory.Navigation, FailureTarget.InertialReference(1)),
        U("navigation.ir.2.disagree", "IR 2 disagree", FailureCategory.Navigation, FailureTarget.InertialReference(2)),
        U("navigation.mcdu.1", "MCDU 1", FailureCategory.Navigation, FailureTarget.Aircraft),
        U("navigation.mcdu.2", "MCDU 2", FailureCategory.Navigation, FailureTarget.Aircraft),
        U("navigation.mcdu.2.recoverable-fault", "MCDU 2 recoverable fault", FailureCategory.Navigation, FailureTarget.Aircraft),
        U("navigation.fmgc.2", "FMGC 2", FailureCategory.Navigation, FailureTarget.Aircraft),
        U("navigation.gpwc", "Ground proximity warning computer", FailureCategory.Navigation, FailureTarget.Aircraft),
        U("navigation.vor.1", "VOR 1", FailureCategory.Navigation, FailureTarget.Aircraft),
        U("navigation.vor.2", "VOR 2", FailureCategory.Navigation, FailureTarget.Aircraft),
        U("navigation.adf.2", "ADF 2", FailureCategory.Navigation, FailureTarget.Aircraft),
        U("navigation.ils.1.glideslope", "ILS 1 glideslope", FailureCategory.Navigation, FailureTarget.Aircraft),
        U("navigation.ils.2.localizer", "ILS 2 localizer", FailureCategory.Navigation, FailureTarget.Aircraft),
        U("navigation.ils.2.glideslope", "ILS 2 glideslope", FailureCategory.Navigation, FailureTarget.Aircraft),
        U("navigation.ils-transmitter.localizer", "Localizer transmitter", FailureCategory.Navigation, FailureTarget.Aircraft),
        U("navigation.ils-transmitter.glideslope", "Glideslope transmitter", FailureCategory.Navigation, FailureTarget.Aircraft),
        U("navigation.gps.2", "GPS 2", FailureCategory.Navigation, FailureTarget.Aircraft),
        U("navigation.radio-altimeter.1", "Radio altimeter 1", FailureCategory.Navigation, FailureTarget.Aircraft),
        U("navigation.radio-altimeter.2", "Radio altimeter 2", FailureCategory.Navigation, FailureTarget.Aircraft),
        U("navigation.accuracy-downgrade", "Navigation accuracy downgrade", FailureCategory.Navigation, FailureTarget.Aircraft),
        U("navigation.tcas", "TCAS", FailureCategory.Navigation, FailureTarget.Aircraft),
        U("navigation.atc.1", "ATC transponder 1", FailureCategory.Navigation, FailureTarget.Aircraft),
        U("navigation.atc.2", "ATC transponder 2", FailureCategory.Navigation, FailureTarget.Aircraft),
        U("pneumatic.lavatory-galley-fan", "Lavatory/galley fan", FailureCategory.Pneumatic, FailureTarget.Aircraft),
        U("pneumatic.hp-valve.1", "Engine 1 HP bleed valve", FailureCategory.Pneumatic, FailureTarget.Aircraft),
        U("pneumatic.hp-valve.2", "Engine 2 HP bleed valve", FailureCategory.Pneumatic, FailureTarget.Aircraft),
        U("pneumatic.ram-air-valve", "Ram air valve", FailureCategory.Pneumatic, FailureTarget.Aircraft),
        U("pneumatic.bleed-valve.2", "Engine 2 bleed valve", FailureCategory.Pneumatic, FailureTarget.Aircraft),
        U("pneumatic.hot-air-valve", "Hot air valve", FailureCategory.Pneumatic, FailureTarget.Aircraft),
        U("pneumatic.bleed.1.low-temperature", "Engine 1 bleed low temperature", FailureCategory.Pneumatic, FailureTarget.Aircraft),
        U("pneumatic.bleed.2.low-temperature", "Engine 2 bleed low temperature", FailureCategory.Pneumatic, FailureTarget.Aircraft),
        U("pneumatic.bmc.1", "Bleed monitoring computer 1", FailureCategory.Pneumatic, FailureTarget.Aircraft),
        U("pneumatic.bmc.2", "Bleed monitoring computer 2", FailureCategory.Pneumatic, FailureTarget.Aircraft),
        U("pneumatic.crossbleed-valve", "Crossbleed valve", FailureCategory.Pneumatic, FailureTarget.Aircraft),
        U("pneumatic.apu-bleed-valve", "APU bleed valve", FailureCategory.Pneumatic, FailureTarget.Aircraft),
        U("pneumatic.pack-valve.1", "Pack 1 flow control valve", FailureCategory.Pneumatic, FailureTarget.Aircraft),
        U("pneumatic.pack-valve.2", "Pack 2 flow control valve", FailureCategory.Pneumatic, FailureTarget.Aircraft),
        U("pneumatic.leak.wing.1", "Bleed leak, engine 1 wing", FailureCategory.Pneumatic, FailureTarget.Aircraft),
        U("pneumatic.leak.wing.2", "Bleed leak, engine 2 wing", FailureCategory.Pneumatic, FailureTarget.Aircraft),
        U("pneumatic.leak.pylon.1", "Bleed leak, engine 1 pylon", FailureCategory.Pneumatic, FailureTarget.Aircraft),
        U("pneumatic.leak.pylon.2", "Bleed leak, engine 2 pylon", FailureCategory.Pneumatic, FailureTarget.Aircraft),
        U("pneumatic.leak.apu", "Bleed leak, APU", FailureCategory.Pneumatic, FailureTarget.Aircraft),
        U("apu.ecb", "APU electronic control box", FailureCategory.Apu, FailureTarget.Apu),
        U("apu.oil.low-level", "APU low oil level", FailureCategory.Apu, FailureTarget.Apu),
        U("apu.fuel-valve", "APU fuel valve", FailureCategory.Apu, FailureTarget.Apu),
        U("communications.stuck-mic.captain", "Captain stuck microphone", FailureCategory.Communications, FailureTarget.Aircraft),
        U("communications.stuck-mic.fo", "First officer stuck microphone", FailureCategory.Communications, FailureTarget.Aircraft),
        U("ice-rain.wing-anti-ice-valve.left", "Left wing anti-ice valve", FailureCategory.IceAndRain, FailureTarget.Aircraft),
        U("ice-rain.wing-anti-ice-valve.right", "Right wing anti-ice valve", FailureCategory.IceAndRain, FailureTarget.Aircraft),
        U("ice-rain.engine-anti-ice-valve.1", "Engine 1 anti-ice valve", FailureCategory.IceAndRain, FailureTarget.Aircraft),
        U("ice-rain.engine-anti-ice-valve.2", "Engine 2 anti-ice valve", FailureCategory.IceAndRain, FailureTarget.Aircraft),
        U("ice-rain.whc.1", "Window heat computer 1", FailureCategory.IceAndRain, FailureTarget.Aircraft),
        U("ice-rain.whc.2", "Window heat computer 2", FailureCategory.IceAndRain, FailureTarget.Aircraft),
        U("ice-rain.aoa-heat.captain", "Captain AOA probe heat", FailureCategory.IceAndRain, FailureTarget.Aircraft),
        U("ice-rain.aoa-heat.fo", "First officer AOA probe heat", FailureCategory.IceAndRain, FailureTarget.Aircraft),
        U("ice-rain.tat-heat.captain", "Captain TAT probe heat", FailureCategory.IceAndRain, FailureTarget.Aircraft),
        U("ice-rain.tat-heat.fo", "First officer TAT probe heat", FailureCategory.IceAndRain, FailureTarget.Aircraft),
        U("ice-rain.tat-heat.standby", "Standby TAT probe heat", FailureCategory.IceAndRain, FailureTarget.Aircraft),
        U("ice-rain.pitot-heat.captain", "Captain pitot heat", FailureCategory.IceAndRain, FailureTarget.Aircraft),
        U("ice-rain.pitot-heat.standby", "Standby pitot heat", FailureCategory.IceAndRain, FailureTarget.Aircraft),
        U("ice-rain.static-heat.captain.left", "Captain left static port heat", FailureCategory.IceAndRain, FailureTarget.Aircraft),
        U("ice-rain.static-heat.captain.right", "Captain right static port heat", FailureCategory.IceAndRain, FailureTarget.Aircraft),
        U("ice-rain.static-heat.fo.left", "First officer left static port heat", FailureCategory.IceAndRain, FailureTarget.Aircraft),
        U("ice-rain.static-heat.fo.right", "First officer right static port heat", FailureCategory.IceAndRain, FailureTarget.Aircraft),
        U("ice-rain.static-heat.standby.left", "Standby left static port heat", FailureCategory.IceAndRain, FailureTarget.Aircraft),
        U("ice-rain.static-heat.standby.right", "Standby right static port heat", FailureCategory.IceAndRain, FailureTarget.Aircraft),
        U("ice-rain.phc.1", "Probe heat computer 1", FailureCategory.IceAndRain, FailureTarget.Aircraft),
        U("ice-rain.phc.2", "Probe heat computer 2", FailureCategory.IceAndRain, FailureTarget.Aircraft),
        U("ice-rain.phc.3", "Probe heat computer 3", FailureCategory.IceAndRain, FailureTarget.Aircraft),
        U("ice-rain.engine-icing.1", "Engine 1 icing", FailureCategory.IceAndRain, FailureTarget.Aircraft),
        U("ice-rain.engine-icing.2", "Engine 2 icing", FailureCategory.IceAndRain, FailureTarget.Aircraft),
        U("flight-controls.ippu.1", "IPPU 1", FailureCategory.FlightControls, FailureTarget.Aircraft),
        U("flight-controls.ippu.2", "IPPU 2", FailureCategory.FlightControls, FailureTarget.Aircraft),
        U("flight-controls.flap.locked", "Flaps locked", FailureCategory.FlightControls, FailureTarget.Aircraft),
        U("flight-controls.slat.locked", "Slats locked", FailureCategory.FlightControls, FailureTarget.Aircraft),
        U("flight-controls.flaps.alignment-fault", "Flap alignment fault", FailureCategory.FlightControls, FailureTarget.Aircraft),
        U("flight-controls.sfcc.1", "SFCC 1", FailureCategory.FlightControls, FailureTarget.Aircraft),
        U("flight-controls.sfcc.2", "SFCC 2", FailureCategory.FlightControls, FailureTarget.Aircraft),
        U("flight-controls.sfcc.1.flap-channel", "SFCC 1 flap channel", FailureCategory.FlightControls, FailureTarget.Aircraft),
        U("flight-controls.sfcc.2.flap-channel", "SFCC 2 flap channel", FailureCategory.FlightControls, FailureTarget.Aircraft),
        U("flight-controls.sfcc.1.slat-channel", "SFCC 1 slat channel", FailureCategory.FlightControls, FailureTarget.Aircraft),
        U("flight-controls.sfcc.2.slat-channel", "SFCC 2 slat channel", FailureCategory.FlightControls, FailureTarget.Aircraft),
        U("flight-controls.elac.1", "ELAC 1", FailureCategory.FlightControls, FailureTarget.Aircraft),
        U("flight-controls.elac.2", "ELAC 2", FailureCategory.FlightControls, FailureTarget.Aircraft),
        U("flight-controls.sec.1", "SEC 1", FailureCategory.FlightControls, FailureTarget.Aircraft),
        U("flight-controls.sec.2", "SEC 2", FailureCategory.FlightControls, FailureTarget.Aircraft),
        U("flight-controls.sec.3", "SEC 3", FailureCategory.FlightControls, FailureTarget.Aircraft),
        U("flight-controls.elac.1.resettable-fault", "ELAC 1 resettable fault", FailureCategory.FlightControls, FailureTarget.Aircraft),
        U("flight-controls.elac.2.resettable-fault", "ELAC 2 resettable fault", FailureCategory.FlightControls, FailureTarget.Aircraft),
        U("flight-controls.sec.1.resettable-fault", "SEC 1 resettable fault", FailureCategory.FlightControls, FailureTarget.Aircraft),
        U("flight-controls.sec.2.resettable-fault", "SEC 2 resettable fault", FailureCategory.FlightControls, FailureTarget.Aircraft),
        U("flight-controls.sec.3.resettable-fault", "SEC 3 resettable fault", FailureCategory.FlightControls, FailureTarget.Aircraft),
        U("flight-controls.yaw-damper.1", "Yaw damper channel 1", FailureCategory.FlightControls, FailureTarget.Aircraft),
        U("flight-controls.yaw-damper.2", "Yaw damper channel 2", FailureCategory.FlightControls, FailureTarget.Aircraft),
        U("flight-controls.sidestick.captain.pitch-reversal", "Captain sidestick pitch reversal", FailureCategory.FlightControls, FailureTarget.Aircraft),
        U("flight-controls.sidestick.captain.roll-reversal", "Captain sidestick roll reversal", FailureCategory.FlightControls, FailureTarget.Aircraft),
        U("flight-controls.sidestick.fo.pitch-reversal", "First officer sidestick pitch reversal", FailureCategory.FlightControls, FailureTarget.Aircraft),
        U("flight-controls.sidestick.fo.roll-reversal", "First officer sidestick roll reversal", FailureCategory.FlightControls, FailureTarget.Aircraft),
        U("flight-controls.sidestick.captain.fault", "Captain sidestick fault", FailureCategory.FlightControls, FailureTarget.Aircraft),
        U("flight-controls.sidestick.fo.fault", "First officer sidestick fault", FailureCategory.FlightControls, FailureTarget.Aircraft),
        U("flight-controls.fcdc.1", "FCDC 1", FailureCategory.FlightControls, FailureTarget.Aircraft),
        U("flight-controls.fcdc.2", "FCDC 2", FailureCategory.FlightControls, FailureTarget.Aircraft),
        U("flight-controls.stabilizer.jam", "Stabilizer jam", FailureCategory.FlightControls, FailureTarget.Aircraft),
        U("flight-controls.elevator.both", "Left and right elevator failure", FailureCategory.FlightControls, FailureTarget.Aircraft),
        U("flight-controls.elevator.left", "Left elevator failure", FailureCategory.FlightControls, FailureTarget.Aircraft),
        U("flight-controls.elevator.right", "Right elevator failure", FailureCategory.FlightControls, FailureTarget.Aircraft),
        U("engine.1.start-valve", "Engine 1 start valve", FailureCategory.Engine, FailureTarget.Engine(1)),
        U("engine.2.start-valve", "Engine 2 start valve", FailureCategory.Engine, FailureTarget.Engine(2)),
        U("engine.1.start.hot", "Engine 1 hot start", FailureCategory.Engine, FailureTarget.Engine(1)),
        U("engine.2.start.hot", "Engine 2 hot start", FailureCategory.Engine, FailureTarget.Engine(2)),
        U("engine.1.start.hung", "Engine 1 hung start", FailureCategory.Engine, FailureTarget.Engine(1)),
        U("engine.2.start.hung", "Engine 2 hung start", FailureCategory.Engine, FailureTarget.Engine(2)),
        U("engine.1.start.no-ignition", "Engine 1 no ignition", FailureCategory.Engine, FailureTarget.Engine(1)),
        U("engine.2.start.no-ignition", "Engine 2 no ignition", FailureCategory.Engine, FailureTarget.Engine(2)),
        U("indicating.cfdiu", "CFDIU", FailureCategory.Instruments, FailureTarget.Aircraft),
        U("indicating.ecp", "ECAM control panel", FailureCategory.Instruments, FailureTarget.Aircraft),
        U("indicating.sdac.1", "SDAC 1", FailureCategory.Instruments, FailureTarget.Aircraft),
        U("indicating.sdac.2", "SDAC 2", FailureCategory.Instruments, FailureTarget.Aircraft),
        U("indicating.fwc.1", "Flight warning computer 1", FailureCategory.Instruments, FailureTarget.Aircraft),
        U("indicating.fwc.2", "Flight warning computer 2", FailureCategory.Instruments, FailureTarget.Aircraft),
        U("indicating.cvr", "Cockpit voice recorder", FailureCategory.Instruments, FailureTarget.Aircraft),
        U("indicating.dmc.1", "Display management computer 1", FailureCategory.Instruments, FailureTarget.Aircraft),
        U("indicating.dmc.2", "Display management computer 2", FailureCategory.Instruments, FailureTarget.Aircraft),
        U("indicating.dmc.3", "Display management computer 3", FailureCategory.Instruments, FailureTarget.Aircraft),
        U("indicating.dcdu.captain", "Captain DCDU", FailureCategory.Instruments, FailureTarget.Aircraft),
        U("indicating.dcdu.fo", "First officer DCDU", FailureCategory.Instruments, FailureTarget.Aircraft),
        U("indicating.display.captain-pfd", "Captain PFD display unit", FailureCategory.Instruments, FailureTarget.Aircraft),
        U("indicating.display.captain-nd", "Captain ND display unit", FailureCategory.Instruments, FailureTarget.Aircraft),
        U("indicating.display.fo-nd", "First officer ND display unit", FailureCategory.Instruments, FailureTarget.Aircraft),
        U("indicating.display.fo-pfd", "First officer PFD display unit", FailureCategory.Instruments, FailureTarget.Aircraft),
        U("indicating.display.ecam-upper", "Upper ECAM display unit", FailureCategory.Instruments, FailureTarget.Aircraft),
        U("oxygen.crew.1.pressure-below-400", "Crew oxygen 1 pressure below 400 psi", FailureCategory.Oxygen, FailureTarget.Aircraft),
        U("oxygen.crew.1.pressure-below-800", "Crew oxygen 1 pressure below 800 psi", FailureCategory.Oxygen, FailureTarget.Aircraft),
        U("oxygen.crew.2.pressure-below-400", "Crew oxygen 2 pressure below 400 psi", FailureCategory.Oxygen, FailureTarget.Aircraft),
        U("oxygen.crew.2.pressure-below-800", "Crew oxygen 2 pressure below 800 psi", FailureCategory.Oxygen, FailureTarget.Aircraft),
        U("oxygen.crew.supply-valve.1", "Crew oxygen supply valve 1", FailureCategory.Oxygen, FailureTarget.Aircraft),
        U("oxygen.crew.supply-valve.2", "Crew oxygen supply valve 2", FailureCategory.Oxygen, FailureTarget.Aircraft),
        U("information.atsu", "ATSU", FailureCategory.Other, FailureTarget.Aircraft),
        U("doors.avionics.forward", "Forward avionics door", FailureCategory.Doors, FailureTarget.Aircraft),
        U("doors.avionics.left", "Left avionics door", FailureCategory.Doors, FailureTarget.Aircraft),
        U("doors.avionics.right", "Right avionics door", FailureCategory.Doors, FailureTarget.Aircraft),
        U("doors.wing.left-1", "Left wing door 1", FailureCategory.Doors, FailureTarget.Aircraft),
        U("doors.wing.left-2", "Left wing door 2", FailureCategory.Doors, FailureTarget.Aircraft),
        U("doors.entry.forward-right", "Forward right entry door", FailureCategory.Doors, FailureTarget.Aircraft),
        U("doors.avionics.aft", "Aft avionics door", FailureCategory.Doors, FailureTarget.Aircraft),
        U("doors.cargo.forward", "Forward cargo door", FailureCategory.Doors, FailureTarget.Aircraft),
        U("doors.wing.right-1", "Right wing door 1", FailureCategory.Doors, FailureTarget.Aircraft),
        U("doors.wing.right-2", "Right wing door 2", FailureCategory.Doors, FailureTarget.Aircraft),
        U("doors.cargo.aft", "Aft cargo door", FailureCategory.Doors, FailureTarget.Aircraft),
        U("doors.cargo.bulk", "Bulk cargo door", FailureCategory.Doors, FailureTarget.Aircraft),
        U("doors.entry.aft-right", "Aft right entry door", FailureCategory.Doors, FailureTarget.Aircraft),
        U("engine.1.fadec.channel-a", "Engine 1 FADEC channel A", FailureCategory.Engine, FailureTarget.Engine(1)),
        U("engine.1.fadec.channel-b", "Engine 1 FADEC channel B", FailureCategory.Engine, FailureTarget.Engine(1)),
        U("engine.2.fadec.channel-a", "Engine 2 FADEC channel A", FailureCategory.Engine, FailureTarget.Engine(2)),
        U("engine.2.fadec.channel-b", "Engine 2 FADEC channel B", FailureCategory.Engine, FailureTarget.Engine(2)),
        U("engine.2.eiu", "Engine 2 interface unit (EIU 2)", FailureCategory.Engine, FailureTarget.Engine(2)),
        U("engine.2.surge", "Engine 2 surge", FailureCategory.Engine, FailureTarget.Engine(2)),
        U("engine.1.failure", "Engine 1 failure", FailureCategory.Engine, FailureTarget.Engine(1)),
        U("engine.2.failure", "Engine 2 failure", FailureCategory.Engine, FailureTarget.Engine(2)),
        U("engine.1.failure-with-damage", "Engine 1 failure with damage", FailureCategory.Engine, FailureTarget.Engine(1)),
        U("engine.2.failure-with-damage", "Engine 2 failure with damage", FailureCategory.Engine, FailureTarget.Engine(2)),
        U("engine.1.bird-strike", "Engine 1 bird strike", FailureCategory.Engine, FailureTarget.Engine(1)),
        U("engine.2.bird-strike", "Engine 2 bird strike", FailureCategory.Engine, FailureTarget.Engine(2)),
        U("engine.1.reverser.pressurized", "Engine 1 reverser pressurized", FailureCategory.Engine, FailureTarget.Engine(1)),
        U("engine.2.reverser.pressurized", "Engine 2 reverser pressurized", FailureCategory.Engine, FailureTarget.Engine(2)),
        U("engine.1.reverser.unlocked", "Engine 1 reverser unlocked", FailureCategory.Engine, FailureTarget.Engine(1)),
        U("engine.2.reverser.unlocked", "Engine 2 reverser unlocked", FailureCategory.Engine, FailureTarget.Engine(2)),
        U("engine.1.reverser.inhibited", "Engine 1 reverser inhibited by maintenance", FailureCategory.Engine, FailureTarget.Engine(1)),
        U("engine.2.reverser.inhibited", "Engine 2 reverser inhibited by maintenance", FailureCategory.Engine, FailureTarget.Engine(2)),
        U("engine.2.vibration.n1", "Engine 2 high N1 vibration", FailureCategory.Engine, FailureTarget.Engine(2)),
        U("engine.1.vibration.n2", "Engine 1 high N2 vibration", FailureCategory.Engine, FailureTarget.Engine(1)),
        U("engine.2.vibration.n2", "Engine 2 high N2 vibration", FailureCategory.Engine, FailureTarget.Engine(2)),
        U("engine.1.oil-leak", "Engine 1 oil leak", FailureCategory.Engine, FailureTarget.Engine(1)),
        U("engine.2.oil-leak", "Engine 2 oil leak", FailureCategory.Engine, FailureTarget.Engine(2)),
        U("engine.1.reverser.shutoff-valve", "Engine 1 reverser shutoff valve", FailureCategory.Engine, FailureTarget.Engine(1)),
        U("engine.2.reverser.shutoff-valve", "Engine 2 reverser shutoff valve", FailureCategory.Engine, FailureTarget.Engine(2)),
    ];

    internal static readonly FailureCatalog Catalog = new(Recipes.Select(r => r.Definition));

    internal static SynapticFailureRecipe? Find(FailureKey key) => Recipes.FirstOrDefault(r => r.Key == key);

    private static SynapticFailureRecipe U(string key, string displayName, FailureCategory category, FailureTarget target) =>
        F(key, displayName, category, target, SynapticFailureQualification.Unmapped, "no documented Synaptic control");

    private static SynapticFailureRecipe F(
        string key,
        string displayName,
        FailureCategory category,
        FailureTarget target,
        SynapticFailureQualification qualification,
        string effect,
        params SynapticControl[] controls) =>
        new(
            new FailureDefinition
            {
                Key = FailureKey.Parse(key),
                DisplayName = displayName,
                Category = category,
                SupportedTargets = [target],
                Operations = controls.Length > 0 ? Both : FailureOperations.None,
            },
            qualification,
            effect,
            controls);
}
